pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: jenkins-agent
spec:
  containers:
  - name: jnlp
    image: local-jenkins-agent:latest
    imagePullPolicy: Never
    securityContext:
      runAsUser: 0
    env:
    - name: DOCKER_API_VERSION
      value: "1.44"
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }

    environment {
        REGISTRY_IMAGE = 'order-service:latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building container image inside Minikube runtime...'
                sh "docker build -t ${REGISTRY_IMAGE} ./apps/order-service"
            }
        }

        stage('Kubernetes Deployment') {
            steps {
                echo 'Applying manifests to local Kubernetes cluster...'
                sh "kubectl apply -f k8s/base/deployment.yaml"
                sh "kubectl apply -f k8s/base/service.yaml"
            }
        }

        stage('Verify Rollout') {
            steps {
                echo 'Checking pod deployment status...'
                sh "kubectl rollout status deployment/order-service --timeout=60s"
            }
        }
    }

    post {
        success {
            echo 'Deployment Pipeline executed successfully! App is active.'
        }
        failure {
            echo 'Pipeline failed. Checking pod status...'
            sh 'kubectl get pods'
        }
    }
}
