pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: jenkins-agent
spec:
  containers:
  - name: docker-cli
    image: docker:cli
    command:
    - sleep
    args:
    - infinity
    env:
    - name: DOCKER_API_VERSION
      value: "1.44"
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: k8s-cli
    image: bitnami/kubectl:latest
    command:
    - sleep
    args:
    - infinity
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }

    environment {
        REGISTRY_IMAGE = 'order-service:latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                container('docker-cli') {
                    echo 'Building container image inside Minikube runtime...'
                    sh "docker build -t ${REGISTRY_IMAGE} ./apps/order-service"
                }
            }
        }

        stage('Kubernetes Deployment') {
            steps {
                container('k8s-cli') {
                    echo 'Applying manifests to local Kubernetes cluster...'
                    sh "kubectl apply -f k8s/base/deployment.yaml"
                    sh "kubectl apply -f k8s/base/service.yaml"
                }
            }
        }

        stage('Verify Rollout') {
            steps {
                container('k8s-cli') {
                    echo 'Checking pod deployment status...'
                    sh "kubectl rollout status deployment/order-service --timeout=60s"
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Pipeline executed successfully! App is active.'
        }
        failure {
            echo 'Pipeline failed. Check pod status:'
            container('k8s-cli') {
                sh 'kubectl get pods'
            }
        }
    }
}
