apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80          # The port accessible inside the cluster
      targetPort: 8000  # The port your FastAPI app listens on inside the container
  type: ClusterIP       # Internal stable IP address
